### PR TITLE
Fix proptest tests

### PR DESCRIPTION
**Pull request by dangrabcad**
After [your comment on issue#20](https://github.com/Alexhuszagh/rust-lexical/issues/20#issuecomment-516523638), I had a look at the existing tests, and I think I found why they're not finding any bugs for you. (Details in the commit message.)

I've run `cargo test` by hand a few times but there haven't been any new failures.

### CODE REVIEW

**Comment by dangrabcad** [comment]
I take back what I said about the new failures: because the Travis runs are on so many platforms they  found some failure cases with my new tests right away.

**Comment by Alexhuszagh** [comment]
@dangrabcad Actually, I merged from quicktest to proptest, so that might explain it. I'm going to search through all the errors that arise and see if any of those are real errors or artfifacts and then accept your PR. Thank you.

**Comment by Alexhuszagh** [comment]
@dangrabcad, these are all artefacts currently because the proptests are running on the disabled-by-default, fast, lossy float parser, which can lead to errors >= 1 ULP. I've tried many of these cases with the correct parser, and none have issues. I would love these test cases however, could you add the following line above all the new proptests and I will accept the PR?

```rust
#[cfg(feature = "correct")]
```

For example:

```rust
        #[cfg(feature = "correct")]
        #[test]
        fn f32_roundtrip_display_proptest(i in f32::MIN..f32::MAX) {
            let input: String = format!("{}", i);
            prop_assert_eq!(i, atof32_slice(input.as_bytes()));
        }
```

Thank you, by the way.

**Comment by dangrabcad** [comment]
I fixed the problem and the tests all passed on this run, but none of the `prop_assert*` calls could compile on nightly Rust. It looks like something might have changed with symbol lookup from macros?

**Comment by dangrabcad** [comment]
Proptest's own tests last ran 3rd Aug on Travis and passed against nightly Rust.

**Comment by Alexhuszagh** [comment]
@dangrabcad I've just discovered proptest has pretty awful support for no_std environments, including regular expression expanding, so I'm ok with disabling proptest in a `no_std` context, since nothing depends intrinsically on `no_std` features.

Here's a patch to fix your commit. Save the following content as `patch.diff` and run `git apply patch.diff` in the repository folder.

```diff
diff --git a/lexical-core/src/atof/api.rs b/lexical-core/src/atof/api.rs
index 0008316..413ec69 100644
--- a/lexical-core/src/atof/api.rs
+++ b/lexical-core/src/atof/api.rs
@@ -400,6 +400,7 @@ mod tests {
         assert_eq!(success(5.002868148396374), try_atof64_slice(b"5.002868148396374"));
     }
 
+    #[cfg(feature = "std")]
     proptest! {
         #[test]
         fn f32_invalid_proptest(i in r"[+-]?[0-9]{2}\D?\.\D?[0-9]{2}\D?e[+-]?[0-9]+\D") {
diff --git a/lexical-core/src/atoi.rs b/lexical-core/src/atoi.rs
index 20c9d6f..031290b 100644
--- a/lexical-core/src/atoi.rs
+++ b/lexical-core/src/atoi.rs
@@ -595,6 +595,7 @@ mod tests {
         assert_eq!(overflow_error(7125759012462002176), try_atoi64_slice(b"6260572000000000000000-3*+\x006666600099000066006660066665?666666666599990000666"));
     }
 
+    #[cfg(feature = "std")]
     proptest! {
         #[test]
         fn u8_invalid_proptest(i in r"[+]?[0-9]{2}\D") {
diff --git a/lexical-core/src/ftoa/api.rs b/lexical-core/src/ftoa/api.rs
index f84a36f..f8ba91d 100644
--- a/lexical-core/src/ftoa/api.rs
+++ b/lexical-core/src/ftoa/api.rs
@@ -456,7 +456,7 @@ mod tests {
         }
     }
 
-    #[cfg(feature = "correct")]
+    #[cfg(all(feature = "correct", feature = "std"))]
     proptest! {
         #[test]
         fn f32_proptest(i in f32::MIN..f32::MAX) {
diff --git a/lexical-core/src/itoa.rs b/lexical-core/src/itoa.rs
index 94ec468..7e6af62 100644
--- a/lexical-core/src/itoa.rs
+++ b/lexical-core/src/itoa.rs
@@ -570,6 +570,7 @@ mod tests {
         }
     }
 
+    #[cfg(feature = "std")]
     proptest! {
         #[test]
         fn u8_proptest(i in u8::min_value()..u8::max_value()) {
diff --git a/lexical-core/src/lib.rs b/lexical-core/src/lib.rs
index f202be0..4d6bcbe 100644
--- a/lexical-core/src/lib.rs
+++ b/lexical-core/src/lib.rs
@@ -120,7 +120,7 @@ extern crate approx;
 extern crate quickcheck;
 
 // Test against randomly-generated guided data.
-#[cfg(test)]
+#[cfg(all(test, feature = "std"))]
 #[macro_use]
 extern crate proptest;
```

**Pull request merged**
